services:
  mariadb:
    image: mariadb:latest
    env_file: [ cyber.env ]
    volumes:
      - ./config/db_schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks: [ connectionator ]

  php:
    build:
      context: .
      dockerfile_inline: |
        FROM php:fpm-alpine
        RUN docker-php-ext-install mysqli
    volumes:
      - /tmp/php-sock.d:/tmp/php-sock.d
      - storage:/var/www/storage
      - ./frontend:/var/www/html:ro
      - ./config/php.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    env_file: [ cyber.env ]
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on: [ mariadb ]
    networks: [ connectionator ]
    command: [ php-fpm, --allow-to-run-as-root ]

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - /tmp/php-sock.d:/var/run/php
      - storage:/www/storage:ro
      - ./frontend:/www/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file: [ cyber.env ]
    depends_on: [ php ]
    networks: [ connectionator ]

  prison:
    build:
      context: .
    privileged: true
    secrets:
      - flag
    volumes:
      - docker-images:/var/lib/docker
    networks: [ connectionator ]


networks:
  connectionator:

volumes:
  storage:
  docker-images:

secrets:
  flag:
    file: ./flag.txt
